video: Fix compile warnings for virgl_video_codec_profile
../src/virgl_video.c:865:25: warning: conflicting types for
'virgl_video_codec_profile' due to enum/integer mismatch;

Signed-off-by: Feng Jiang <jiangfeng@kylinos.cn>
Reviewed-by: Daniel Almeida <daniel.almeida@collabora.com>
Part-of: <https://gitlab.freedesktop.org/virgl/virglrenderer/-/merge_requests/1135>